services:
  # Main web application
  - type: web
    name: swarm-agents-web
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --worker-class eventlet src.main:app
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: swarm-agents-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: swarm-agents-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: HOST
        value: "0.0.0.0"
      - key: API_TIMEOUT
        value: "30"
      - key: MAX_RETRIES
        value: "3"
      - key: RATE_LIMIT_PER_MINUTE
        value: "60"
      - key: MAX_CONVERSATION_CONTEXT
        value: "20"

  # PostgreSQL Database
  - type: pserv
    name: swarm-agents-db
    env: postgresql
    region: oregon
    plan: starter
    databaseName: swarm_agents
    databaseUser: swarm_user

  # Redis Cache
  - type: redis
    name: swarm-agents-redis
    region: oregon
    plan: starter

