services:
  - type: web
    name: swarm-agents-web
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 src.main:app
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: "10000"
      - key: API_TIMEOUT
        value: "30"
      - key: MAX_RETRIES
        value: "3"
      - key: RATE_LIMIT_PER_MINUTE
        value: "60"
      - key: MAX_CONVERSATION_CONTEXT
        value: "20"
      - key: DATABASE_URL
        fromDatabase:
          name: swarm-agents-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: swarm-agents-redis
          property: connectionString
      # Secrets: fill these on the Render dashboard after first deploy
      - key: SECRET_KEY
        value: ""
      - key: OPENROUTER_API_KEY
        value: ""
      - key: SUPERMEMORY_API_KEY
        value: ""
      - key: MAILGUN_API_KEY
        value: ""
      - key: MAILGUN_DOMAIN
        value: ""
      - key: MAILGUN_WEBHOOK_SIGNING_KEY
        value: ""
      - key: MAILGUN_SENDING_KEY
        value: ""

  - type: redis
    name: swarm-agents-redis
    region: oregon
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

databases:
  - name: swarm-agents-db
    databaseName: swarm_agents
    user: swarm_user
    region: oregon
    plan: basic-256