services:
  - type: web
    name: swarm-agents-web
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 src.main:app
    postDeployCommand: python migrate_db.py         # <-- Add if you want DB migrations to run after deploy!
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      # Non-secret config (safe in YAML)
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: "10000"
      - key: API_TIMEOUT
        value: "30"
      - key: MAX_RETRIES
        value: "3"
      - key: RATE_LIMIT_PER_MINUTE
        value: "60"
      - key: MAX_CONVERSATION_CONTEXT
        value: "20"
      # DB/Redis will be auto-populated from service creation:
      - key: DATABASE_URL
        fromDatabase:
          name: swarm-agents-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: swarm-agents-redis
          property: connectionString
      # Everything below should be set as secrets in the dashboard after first deploy (leave value blank or dummy):
      - key: SECRET_KEY
        value: ""
      - key: OPENROUTER_API_KEY
        value: ""
      - key: SUPERMEMORY_API_KEY
        value: ""
      - key: MAILGUN_API_KEY
        value: ""
      - key: MAILGUN_DOMAIN
        value: ""
      - key: MAILGUN_WEBHOOK_SIGNING_KEY
        value: ""
      - key: MAILGUN_SENDING_KEY
        value: ""

  - type: pserv
    name: swarm-agents-db
    env: postgresql
    region: oregon
    plan: starter
    databaseName: swarm_agents
    databaseUser: swarm_user

  - type: redis
    name: swarm-agents-redis
    region: oregon
    plan: starter
